### ISSUE TITLE
Extra box often created not in original svg

### ISSUE THREAD

**Issue by jaywarfield** [jgraph/svg2xml#25]
For svg files that are converted to xml, svg2xml (latest version) with default options (same result by unchecking the calculate border) adds an extra box to the end of each icon in the xml:

```
    <rect h="32" w="32" x="0.005" y="0"/>
    <fillstroke/>
    </foreground>
</shape> 
```

This is an example svg that results in the above extra rect stmt at end of xml (extra square covers entire icon in this case):

`<svg id="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><defs><style>.cls-1{fill:none;}</style></defs><title>user</title><path d="M16,4a5,5,0,1,1-5,5,5,5,0,0,1,5-5m0-2a7,7,0,1,0,7,7A7,7,0,0,0,16,2Z"/><path d="M26,30H24V25a5,5,0,0,0-5-5H13a5,5,0,0,0-5,5v5H6V25a7,7,0,0,1,7-7h6a7,7,0,0,1,7,7Z"/><rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" class="cls-1" width="32" height="32"/></svg>`

Most of the svg icons I convert by svg2xml have the extra rect as above example.  
A few of the conversions have no extra box.  
A few of the conversions have the following code for the extra box.  

```
     <path>
            <move x="0" y="0"/>
            <line x="0" y="32"/>
            <line x="32" y="32"/>
            <line x="32" y="0"/>
            <line x="0" y="0"/>
            <close/>
        </path>
        <fillstroke/>
    </foreground>
</shape>
```

This is an example svg that results in the above extra path stmts added at end of xml (extra square is in upper left of icon) using 64x64 but also tried 32x32:

`<svg id="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><defs><style>.cls-1{fill:none;}</style></defs><title>network--2</title><path d="M17,17h5.1421a4,4,0,1,0,0-2H17V7h5.1421a4,4,0,1,0,0-2H17a2.0023,2.0023,0,0,0-2,2v8H9.8579a4,4,0,1,0,0,2H15v8a2.0023,2.0023,0,0,0,2,2h5.1421a4,4,0,1,0,0-2H17Zm9-3a2,2,0,1,1-2,2A2.0023,2.0023,0,0,1,26,14ZM26,4a2,2,0,1,1-2,2A2.0023,2.0023,0,0,1,26,4ZM6,18a2,2,0,1,1,2-2A2.0023,2.0023,0,0,1,6,18Zm20,6a2,2,0,1,1-2,2A2.0023,2.0023,0,0,1,26,24Z"/><rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" class="cls-1" width="32" height="32" transform="translate(32 32) rotate(180)"/></svg>`

To remove the extra boxes I go thru each icon in the xml and manually delete the code causing the extra box, but if there is a reason why the extra box code is appearing please let me know.  

This is also mentioned on the group here:
https://groups.google.com/g/drawio/c/-BWlV-tjsTo/m/N-RAuu4iBAAJ

Thanks!

**Comment by jaywarfield-developer** [comment]
Closing out as user error per discussion in the group.  Thanks!
