### ISSUE TITLE
Change fill color of imported SVG

### ISSUE THREAD

**Issue by alelordelo** [jgraph/svg2xml#3]
Seems like it's not possible to change fill color of an imported SVG (using svg2xml), only it's border color.

https://gyazo.com/ea850d6924cabcb4452b4f7d504b6d66

Any tips on how I can change it's fill color?

**Comment by kutya** [comment]
You have to manually remove fill color style for that shape in the svg. Every style that isn't defined for a shape in SVG (fill, stroke, opacity etc), becomes "style flexible" in draw.io.
If it bothers you that the shape becomes black, you can use custom fill from a CSS and reference it in the SVG. svg2xml doesn't take into account CSS references.

**Comment by alelordelo** [comment]
Thanks Mate,
The problem is that I have tens of thousands of colored EPS (Adobe Illustrator) files that I need to export as SVG, and then import to Mxgraph using svg2xml. Then I need to properly manipulate those fill colors. 

it's not possible to that that using svg2xml then?

**Comment by kutya** [comment]
No, it is beyond the limits of svg2xml. If you want to remove all color from all files, you could quickly write some code for it. If that is not the case, the problem is much more complex, that's why svg2xml doesn't support that.

**Comment by alelordelo** [comment]
wow, bad news! : (

This totally kills my project... Do you think of any other alternative that I could import colored EPS/SVG and be able to edit the colors?

**Comment by kutya** [comment]
Not really. The problem is how to artificially define what color would you keep in an SVG and what should be changeable.

**Comment by alelordelo** [comment]
Thanks for helping Mate! : )

Sorry, I didn't understand the problem. You mean "how to artificially define what color would you keepin an SVG and what should be changeable." when importing the SVG? 

But the goal is to keep all colors when imported, right? 

Then you can select each one and change it.This is the default behavior of tools like canva.com or the one I previously used for ex:
https://gyazo.com/350a15f1a8acb28fa6a5f81a81dae1ee

Do yo belice it should be possible to achieve this functionality?

thanks!

**Comment by kutya** [comment]
Draw.io is not a SVG or stencil editor. It uses one fill color, one stroke color for the whole stencil. It's not really like SVG. So for every graphical element of a SVG (path, line etc), if fill is defined, it will be translated into our format. For all elements that have undefined fill, the fill color from draw.io will be applied.

**Comment by alelordelo** [comment]
OMG, I wish the freelancer I hired had told me this, before we started the project.. I'm screwed now... : (

So, the only way to be able to change colors is to import "no fill" SVG files individually, and then apply fill color inside draw.io right?  This would be a "project killer"  since I will have +100K Svgs to upload...

Any workaround you can think of?

**Comment by alelordelo** [comment]
Hi Kutya,

After a lot of sweat, I managed to:

Import an SVG preserving it's color (NOT transparent) and change ALL COLORS to a single color
https://gyazo.com/76b895c200043636e4bcf7f1346b8134

Getting closer to what I need! : )

How, is there a way I can get  a color "bucket fill" for EACH COLOR  and replace it?

**Comment by kutya** [comment]
Example image:
[https://maxcdn.icons8.com/Share/icon/Logos//google_logo1600.png](url)
Since draw.io supports only one fill color, in this case you have to decide which is the one that you want to change. Let's say the blue. You leave all other as is, and remove only the blue fill style in the SVG. Once you import it to draw.io, all colors will be fixed and if you change fill color in draw.io only the old blue part will be changed.

**Comment by kutya** [comment]
Regarding your example, you removed stroke color and that's why you can change it. It would be same for fill color, you can have only ONE changeable fill color per shape.

**Comment by kutya** [comment]
You can have only one changeable fill color per stencil.

**Comment by alelordelo** [comment]
Thanks Mate!

But if draw supports only one color per shape, how am I able to import the "G" logo SVG preserving all colors?
https://gyazo.com/f676cb7c897702875484e90041423838


With the colors inside draw, mas there is  a way to hack and get each color as a "fill color"???
https://gyazo.com/cfa2f32ffb36ff0eba67d89b90faae21

**Comment by kutya** [comment]
"But if draw supports only one color per shape, how am I able to import the
"G" logo SVG preserving all colors?"
Just import it with colors. But then, you won't be able to change them.

"With the colors inside draw, mas there is a way to hack and get each color
as a "fill color"???"
No

**Comment by muthu32** [comment]
SVG as fill color is possible in sketchpad (sketch.io).This is very nicely implemented in sketchpad apps.

https://gyazo.com/ac84dc793caddade4f0f3f60bdd1edea

But it seems draw.io supports single color per svg.
