### ISSUE TITLE
Import SVG with separate layers

### ISSUE THREAD

**Issue by alelordelo** [jgraph/svg2xml#4]
Is it possible to import an SVG with SEPARATE LAYERS, and have each layer as a INDIVIDUAL SHAPE inside mxgraph?

**Comment by alderg** [comment]
The importer is for transforming SVG to our internal stencil format. You'd have to import the SVG in mxgraph or draw.io. In general, given your questions here, the app (draw.io) is probably not ideal for what you are trying to achieve. The good news is that the app can be customized via plugins, and in this case, parsing the svg and generating one shape per layer could be done with a plugin.

**Comment by alelordelo** [comment]
Huge thanks for the fast replies Gaudenz! : )

 You are right that draw.io  may not be ideal to what I am trying to achieve. But we only found about those limitations at the end of the project... 

I am working on a editor like Canva, and for this I need to import a n SVG, and be able to change it's color, edit text, delete parts, etc
 https://www.canva.com

Should be relatively easy to build such  plugins? 

 1- Generates one shape per layer
2- Extract SVG color, changes each color

**Comment by mingjinc** [comment]
Any existed plugins now? We also have requirement on it.

**Comment by alelordelo** [comment]
Ming Jin, I have a JS code that may help with that (Extract SVG color, changes each color). You can reach me on Skype if you want: alelordelo
