### ISSUE TITLE
Is there any plan to support mutiple shape extract?

### ISSUE THREAD

**Issue by mingjinc** [jgraph/svg2xml#6]
We have a standard svg file, wonder to extract mutiple shapes through svg2xml, but only one shape is extracted. We saw the tool has some TODO in config, any plan about them?

**Comment by kutya** [comment]
Multiple shapes are supported, just not obvious, since svg2xml was developed for internal use at that time. Select a folder and all svgs in it should be converted, including subfolders. TODO's are put on hold for now.

**Comment by mingjinc** [comment]
It is good that we can convert each svg to shape xml. Is it an api or tool we convert a svg diagram(with mutiple circles, lines... etc) to mxgraph diagram xml? 
We are struggling to find a solution on how to convert a svg diagram to mxgraph diagram.

**Comment by davidjgraph** [comment]
You cannot convert an SVG representation of a diagram, it does not contain connection information.
