### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by Yarisrespect** [jgraph/svg2xml#8]
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)

Following command "java -jar mxgraph-core.jar" does not lounch app 

Could you help?

**Comment by alderg** [comment]
See https://github.com/jgraph/svg2xml/
